package io.droidbot.vlucide.generator;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

/**
 * Reads Lucide icon metadata and SVG files from the local node_modules
 * directory (installed via npm / frontend-maven-plugin), then generates:
 * <ul>
 * <li>{@code LucideIcon.java} — an enum of all icons</li>
 * <li>SVG files under {@code META-INF/resources/lucide/}</li>
 * </ul>
 * <p>
 * Run from the project root:
 * 
 * <pre>{@code
 * mvn -pl lucide-icons-generator exec:java
 * }</pre>
 */
public class IconGenerator {

	private static final String GENERATED_HEADER = "/*\n"
			+ " * This file is auto-generated by the lucide-icons-generator module.\n"
			+ " * Do not edit by hand. Run `mvn -pl lucide-icons-generator exec:java` to regenerate.\n" + " */\n";

	private final Path runtimeResourcesDir;
	private final Path runtimeJavaDir;

	/**
	 * Constructor.
	 *
	 * @param runtimeResourcesDir path to {@code lucide-icons/src/main/resources}
	 * @param runtimeJavaDir      path to {@code lucide-icons/src/main/java}
	 */
	public IconGenerator(Path runtimeResourcesDir, Path runtimeJavaDir) {
		this.runtimeResourcesDir = runtimeResourcesDir;
		this.runtimeJavaDir = runtimeJavaDir;
	}

	public static void main(String[] args) throws Exception {
		Path projectRoot = findProjectRoot();
		Path resourcesDir = projectRoot.resolve("lucide-icons/src/main/resources");
		Path javaDir = projectRoot.resolve("lucide-icons/src/main/java");

		IconGenerator generator = new IconGenerator(resourcesDir, javaDir);
		generator.run();
	}

	/**
	 * Finds the project root by walking up from the working directory looking for
	 * the parent POM.
	 */
	static Path findProjectRoot() {
		Path current = Paths.get(".").toAbsolutePath().normalize();
		while (current != null) {
			if (Files.exists(current.resolve("pom.xml"))) {
				try {
					String content = Files.readString(current.resolve("pom.xml"));
					if (content.contains("vaadin-lucide-icons-parent")) {
						return current;
					}
				} catch (IOException ignored) {
				}
			}
			current = current.getParent();
		}
		throw new IllegalStateException(
				"Could not find project root (containing parent POM with vaadin-lucide-icons-parent). "
						+ "Run from the project root directory.");
	}

	/**
	 * Runs the full generation pipeline.
	 */
	public void run() throws Exception {
		System.out.println("=== Lucide Icon Generator ===");
		System.out.println("Reading local icon metadata from node_modules...");
		Map<String, List<String>> tagsMap = fetchTags();
		List<String> iconNames = new ArrayList<>(tagsMap.keySet());
		iconNames.sort(Comparator.naturalOrder());
		System.out.println("Found " + iconNames.size() + " icons.");

		Path svgTargetDir = runtimeResourcesDir.resolve("META-INF/resources/lucide");
		Files.createDirectories(svgTargetDir);

		System.out.println("Processing and copying SVG files...");
		Path iconsSrcDir = findProjectRoot().resolve("lucide-icons-generator/node_modules/lucide-static/icons");
		if (!Files.exists(iconsSrcDir)) {
			throw new IOException("Could not find icons directory. Make sure npm install was run first (expected at: " + iconsSrcDir + ")");
		}

		int processed = 0;
		for (String name : iconNames) {
			Path srcPath = iconsSrcDir.resolve(name + ".svg");
			Path targetPath = svgTargetDir.resolve(name + ".svg");
			try {
				if (!Files.exists(srcPath)) {
					System.err.println("  WARN: source icon '" + name + "' not found at: " + srcPath);
					continue;
				}
				String raw = Files.readString(srcPath, StandardCharsets.UTF_8);
				String normalized = normalizeSvg(raw);
				Files.writeString(targetPath, normalized, StandardCharsets.UTF_8);
				processed++;
			} catch (Exception e) {
				System.err.println("  WARN: failed to process '" + name + "': " + e.getMessage());
			}
		}
		System.out.println("SVGs: " + processed + " processed and written to target resources.");

		System.out.println("Generating LucideIcon.java...");
		generateEnum(iconNames, tagsMap);

		System.out.println("=== Done ===");
	}

	/**
	 * Reads {@code tags.json} from the local node_modules directory.
	 */
	Map<String, List<String>> fetchTags() throws Exception {
		Path tagsJsonFile = findProjectRoot().resolve("lucide-icons-generator/node_modules/lucide-static/tags.json");
		if (!Files.exists(tagsJsonFile)) {
			throw new IOException("Could not find tags.json. Make sure npm install was run first (expected at: " + tagsJsonFile + ")");
		}
		String json = Files.readString(tagsJsonFile, StandardCharsets.UTF_8);
		JsonObject root = JsonParser.parseString(json).getAsJsonObject();
		Map<String, List<String>> result = new TreeMap<>();
		for (Map.Entry<String, JsonElement> entry : root.entrySet()) {
			List<String> tags = new ArrayList<>();
			for (JsonElement tag : entry.getValue().getAsJsonArray()) {
				tags.add(tag.getAsString());
			}
			result.put(entry.getKey(), tags);
		}
		return result;
	}

	/**
	 * Normalizes SVG content for use with the {@code <vaadin-icon>} web component.
	 * <p>
	 * Normalization:
	 * <ul>
	 * <li>Strips XML declarations ({@code <?xml ...?>})</li>
	 * <li>Strips {@code width} and {@code height} attributes from the root
	 * {@code <svg>} element (the {@code <vaadin-icon>} web component controls
	 * sizing via CSS)</li>
	 * <li>Strips HTML comments</li>
	 * <li>Normalizes line endings to LF</li>
	 * </ul>
	 */
	static String normalizeSvg(String svg) {
		String result = svg;
		// Remove XML declaration (case-insensitive, optional whitespace/newlines)
		result = result.replaceAll("(?i)<\\?xml[^>]*\\?>", "").trim();
		
		// Remove width/height attributes from the root <svg> element.
		// Uses regex that handles single/double/no quotes and decimal/integer sizes + optional units.
		result = result.replaceAll("(?i)\\s+width\\s*=\\s*['\"]?\\d+(?:\\.\\d+)?(?:px|em|%)?['\"]?", "");
		result = result.replaceAll("(?i)\\s+height\\s*=\\s*['\"]?\\d+(?:\\.\\d+)?(?:px|em|%)?['\"]?", "");
		
		// Remove HTML/XML comments
		result = result.replaceAll("(?i)<!--[\\s\\S]*?-->", "");
		
		// Normalize line endings
		result = result.replace("\r\n", "\n").replace("\r", "\n");
		return result.trim();
	}

	/**
	 * Generates the {@code LucideIcon.java} enum file.
	 */
	void generateEnum(List<String> iconNames, Map<String, List<String>> tagsMap) throws Exception {
		Path packageDir = runtimeJavaDir.resolve("io/droidbot/vlucide");
		Files.createDirectories(packageDir);
		Path enumFile = packageDir.resolve("LucideIcon.java");

		StringBuilder sb = new StringBuilder();
		sb.append("package io.droidbot.vlucide;\n\n");
		sb.append(GENERATED_HEADER);
		sb.append("\n");
		sb.append("/**\n");
		sb.append(" * Enum of all available Lucide icons.\n");
		sb.append(" * <p>\n");
		sb.append(" * Each constant corresponds to an icon in the Lucide icon set.\n");
		sb.append(" * Use {@link #create()} to obtain a {@link LucideSvgIcon} instance.\n");
		sb.append(" *\n");
		sb.append(" * @see <a href=\"https://lucide.dev\">Lucide</a>\n");
		sb.append(" */\n");
		sb.append("public enum LucideIcon {\n\n");

		// Enum constants
		for (int i = 0; i < iconNames.size(); i++) {
			String name = iconNames.get(i);
			String constantName = toEnumConstant(name);
			List<String> tags = tagsMap.getOrDefault(name, List.of());

			sb.append("    /** ").append(String.join(", ", tags)).append(" */\n");
			sb.append("    ").append(constantName).append("(\"").append(name).append("\")");
			if (i < iconNames.size() - 1) {
				sb.append(",");
			} else {
				sb.append(";");
			}
			sb.append("\n\n");
		}

		// Fields and constructor
		sb.append("    private final String iconName;\n\n");
		sb.append("    LucideIcon(String iconName) {\n");
		sb.append("        this.iconName = iconName;\n");
		sb.append("    }\n\n");

		// getIconName()
		sb.append("    /**\n");
		sb.append("     * Returns the Lucide icon file name (without {@code .svg} extension).\n");
		sb.append("     *\n");
		sb.append("     * @return the icon name in kebab-case\n");
		sb.append("     */\n");
		sb.append("    public String getIconName() {\n");
		sb.append("        return iconName;\n");
		sb.append("    }\n\n");

		// create()
		sb.append("    /**\n");
		sb.append("     * Creates a new {@link LucideSvgIcon} for this icon.\n");
		sb.append("     *\n");
		sb.append("     * @return a new icon component\n");
		sb.append("     */\n");
		sb.append("    public LucideSvgIcon create() {\n");
		sb.append("        return LucideIconFactory.create(iconName);\n");
		sb.append("    }\n");

		sb.append("}\n");

		Files.writeString(enumFile, sb.toString(), StandardCharsets.UTF_8);
		System.out.println("Wrote " + enumFile);
	}

	/**
	 * Converts a kebab-case icon name to a Java enum constant.
	 * <p>
	 * Examples:
	 * <ul>
	 * <li>{@code arrow-left} → {@code ARROW_LEFT}</li>
	 * <li>{@code user-round} → {@code USER_ROUND}</li>
	 * </ul>
	 */
	static String toEnumConstant(String kebabCase) {
		String result = kebabCase.replace("-", "_").toUpperCase(java.util.Locale.ROOT);
		if (result.matches("^\\d.*")) {
			result = "_" + result;
		}
		return result;
	}
}
